version: 0.2

# for info on the build phases used here:
#   http://docs.aws.amazon.com/codebuild/latest/userguide/view-build-details.html#view-build-details-phases

# for info on the buildspec.yml syntax:
#   http://docs.aws.amazon.com/codebuild/latest/userguide/build-spec-ref.html

env:
  variables:
    REPO: "nsolid-npm"

phases:
  install:
    commands:
      - npm install

  pre_build:
    commands:
      - mkdir /root/artifacts

  build:
    commands:
      # linting, building, checking deps, checking dep licenses
      - npm test
      
  post_build:
    commands:
      - tar -zcvf coverage-nsolid-npm.tar.gz coverage/
      - mv coverage-nsolid-npm.tar.gz /root/artifacts/ || true

artifacts:
  files:
    - /root/artifacts/*
  discard-paths: yes
